language: ruby
rvm:
  - 2.6.3
cache: bundler

install:
  # Install the right version of Bundler
  # from https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html
  - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
  - make install

script:
  - make lint
  - make build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _site
  target-branch: gh-pages
  fqdn: deadrooster.org
  on:
    branch: master
